name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  envied: ^0.3.0+3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.8
  envied_generator: ^0.3.0+3
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.4.0

flutter_gen:
  output: lib/src/assets/
  integrations:
    flutter_svg: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  assets:
    - assets/color/
    - assets/image/
    - assets/lottie/
    - assets/icons/
